---
# Configuration for Alacritty, the GPU enhanced terminal emulator.
# macOS specific settings.

# Linux specific settings
# Since imported files are lower precedent, the config is symlinked to the os-specific
# config in local/share/alacritty, which in turn imports the config in config/alacritty/.

# Import additional configuration files
#
# Imports are loaded in order, skipping all missing files, with the importing
# file being loaded last. If a field is already present in a previous import, it
# will be replaced.
#
# All imports must either be absolute paths starting with `/`, or paths relative
# to the user's home directory starting with `~/`.
#import:
#  - /path/to/alacritty.yml
# https://github.com/alacritty/alacritty-theme
import:
  - ~/projects/dotfiles/config/alacritty/alacritty.yml

# macOS has a higher resolution (1680x1060)
font:
  size: 12.0

window:
  # Window dimensions (changes require restart)
  #
  # Number of lines/columns (not pixels) in the terminal. Both lines and columns
  # must be non-zero for this to take effect. The number of columns must be at
  # least `2`, while using a value of `0` for columns and lines will fall back
  # to the window manager's recommended size
  # Retina (2560x1600) display with 2 terminals wide and 2 terminals high.
  dimensions:
    columns: 120
    lines: 38

# Any items in the `env` entry below will be added as environment variables.
# Some entries may override variables set by alacritty itself.
env:

  # PATH variable
  #
  # Alacritty on the Mac has a very basic $PATH which does not include the extra paths added in .bashrc.
  # This $PATH variable sets the path similar to .bashrc.
  PATH: /usr/local/bin:/opt/homebrew/opt/coreutils/libexec/gnubin:/usr/bin:/bin:/usr/sbin:/sbin:~/bin:~/go/bin:~/.cargo/bin:~/.local/bin:~/.rd/bin:/opt/homebrew/bin
  # Here's the original path using bash and .bashrc
  #   /opt/homebrew/opt/coreutils/libexec/gnubin
  #   /usr/local/bin
  #   /System/Cryptexes/App/usr/bin
  #   /usr/bin
  #   /bin
  #   /usr/sbin
  #   /sbin
  #   /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
  #   /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
  #   /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
  #   /Users/dev/.cargo/bin
  #   /Users/dev/bin
  #   /Users/dev/go/bin
  #   /Users/dev/.local/bin
  #   /Users/dev/.rd/bin
  #   /Users/dev/projects/server-profile/bin
  #   /Users/dev/projects/dotfiles/bin
  #   /Users/dev
  #   /opt/homebrew/bin
